theme: jekyll-theme-cayman
title: Hinode Code
description: Trying to do stuff and write about it
show_downloads: false
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - RAYCASTING001.md
highlighter: c
