theme: jekyll-theme-tactile
title: Hinode Code
description: Trying to do stuff and write about it
show_downloads: false
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - RAYCASTING001.md
C:
  type: programming
  color: "#555555"
  extensions:
  - ".c"
  - ".cats"
  - ".h"
  - ".idc"
  interpreters:
  - tcc
  tm_scope: source.c
  ace_mode: c_cpp
  codemirror_mode: clike
  codemirror_mime_type: text/x-csrc
  language_id: 41
